name: Release on tag

on:
  push:
    tags:
      - v*

jobs:
  build-ubuntu:
    name: "Release Notes"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Setup Repo
      - name: Checkout
        uses: actions/checkout@v4

      # Create tag based changelog
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,ci

      # Create release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }}

      - name: Debug output
        run: |
          ls
